### ISSUE TITLE
Migrate "request" to "axios"

### ISSUE THREAD

**Issue by AlonMiz** [logzio/logzio-nodejs#89]
`request` module is considered deprecated and is accumulating up security vulnerabilities.
suggesting migration to Axios, which shouldn't be much effort.

https://www.npmjs.com/package/request
![image](https://user-images.githubusercontent.com/1812912/97189083-e349a400-17ac-11eb-93e5-85cf8e7135d1.png)

**Comment by ukmadlz** [comment]
Is it worth consider `node-fetch`?

**Comment by AlonMiz** [comment]
yes, indeed. i think it might be even better, as it has a consist API with the browser, and might have a longer lifetime

**Comment by darcyparker** [comment]
Definitely need to migrate from 'request'. And I second using `node-fetch` over `axios`. 

`axios`'s advantage is that its isomorphic for browser/node.  But it is a new API... and `logzio-nodejs` is not for browser because it uses `dgram.createSocket('udp4')`.  `axios`'s API is not that hard to understand and probably easy to port in future... but its not a standard like `node-fetch`.

As well, as https://github.com/node-fetch/node-fetch#motivation points out, `isomorphic-unfetch` and `cross-fetch` use `node-fetch`.  So if `logzio-nodejs` ever needs to support a browser, I'd use say `cross-fetch`.

**Comment by Sujay-shetty** [comment]
@AlonMiz, @yotamloe  is there any plan to upgrade request package as there is a critical vulnerability found on json-schema which is been used by request package.
https://nvd.nist.gov/vuln/detail/CVE-2021-3918

**Comment by AlonMiz** [comment]
@Doron-Bargo can you consider fixing that?

**Comment by Sujay-shetty** [comment]
@AlonMiz , @Doron-Bargo any update on this, could you please consider this migration, as criticality is 9.8?

**Comment by AlonMiz** [comment]
hi @Sujay-shetty, it's not a quick migration. most of the unit tests infra are based on the `request` mechanism.
but, we would love to have a PR for that.
node-fetch and axios. both sound like a good fit.
@Doron-Bargo any comments?

**Comment by kaushikthommandra** [comment]
any update on this?

**Comment by Doron-Bargo** [comment]
https://github.com/logzio/logzio-nodejs/pull/97

**Comment by resdenia** [comment]
Logzio-nodejs v2.1.4 migrated from request to axios related [PR](https://github.com/logzio/logzio-nodejs/pull/97)
